insert into SYSTEM.VOLUNTEERS (VOLUNTEER_ID, JOIN_DATE, NAME, ROLE_ID, GEAR_ID, PHONE_NUMBER)
values (547431039, to_date('14-04-2023', 'dd-mm-yyyy'), 'EdgarMacy', (SELECT * FROM (SELECT Role_id FROM Position ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT GEAR_ID FROM GEAR ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1)), (SELECT * FROM (SELECT PHONE_NUMBER FROM PERSONAL_INFO ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.VOLUNTEERS (VOLUNTEER_ID, JOIN_DATE, NAME, ROLE_ID, GEAR_ID, PHONE_NUMBER)
values (657300626, to_date('07-03-2023', 'dd-mm-yyyy'), 'NickCumming', (SELECT * FROM (SELECT Role_id FROM Position ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT GEAR_ID FROM GEAR ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1)), (SELECT * FROM (SELECT PHONE_NUMBER FROM PERSONAL_INFO ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.VOLUNTEERS (VOLUNTEER_ID, JOIN_DATE, NAME, ROLE_ID, GEAR_ID, PHONE_NUMBER)
values (634184425, to_date('30-04-2023', 'dd-mm-yyyy'), 'MykeltiNeill', (SELECT * FROM (SELECT Role_id FROM Position ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT GEAR_ID FROM GEAR ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1)), (SELECT * FROM (SELECT PHONE_NUMBER FROM PERSONAL_INFO ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.VOLUNTEERS (VOLUNTEER_ID, JOIN_DATE, NAME, ROLE_ID, GEAR_ID, PHONE_NUMBER)
values (961217161, to_date('19-11-2023', 'dd-mm-yyyy'), 'BurtonPlummer', (SELECT * FROM (SELECT Role_id FROM Position ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT GEAR_ID FROM GEAR ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1)), (SELECT * FROM (SELECT PHONE_NUMBER FROM PERSONAL_INFO ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.VOLUNTEERS (VOLUNTEER_ID, JOIN_DATE, NAME, ROLE_ID, GEAR_ID, PHONE_NUMBER)
values (472502869, to_date('30-03-2023', 'dd-mm-yyyy'), 'AngelaShort', (SELECT * FROM (SELECT Role_id FROM Position ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT GEAR_ID FROM GEAR ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1)), (SELECT * FROM (SELECT PHONE_NUMBER FROM PERSONAL_INFO ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.VOLUNTEERS (VOLUNTEER_ID, JOIN_DATE, NAME, ROLE_ID, GEAR_ID, PHONE_NUMBER)
values (797029697, to_date('25-11-2023', 'dd-mm-yyyy'), 'TziDolenz', (SELECT * FROM (SELECT Role_id FROM Position ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT GEAR_ID FROM GEAR ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1)), (SELECT * FROM (SELECT PHONE_NUMBER FROM PERSONAL_INFO ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.VOLUNTEERS (VOLUNTEER_ID, JOIN_DATE, NAME, ROLE_ID, GEAR_ID, PHONE_NUMBER)
values (780416728, to_date('31-08-2023', 'dd-mm-yyyy'), 'PamGellar', (SELECT * FROM (SELECT Role_id FROM Position ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT GEAR_ID FROM GEAR ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1)), (SELECT * FROM (SELECT PHONE_NUMBER FROM PERSONAL_INFO ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.VOLUNTEERS (VOLUNTEER_ID, JOIN_DATE, NAME, ROLE_ID, GEAR_ID, PHONE_NUMBER)
values (951680335, to_date('26-08-2023', 'dd-mm-yyyy'), 'LydiaBiel', (SELECT * FROM (SELECT Role_id FROM Position ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT GEAR_ID FROM GEAR ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1)), (SELECT * FROM (SELECT PHONE_NUMBER FROM PERSONAL_INFO ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.VOLUNTEERS (VOLUNTEER_ID, JOIN_DATE, NAME, ROLE_ID, GEAR_ID, PHONE_NUMBER)
values (527207578, to_date('30-10-2023', 'dd-mm-yyyy'), 'PamelaVan Der Beek', (SELECT * FROM (SELECT Role_id FROM Position ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT GEAR_ID FROM GEAR ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1)), (SELECT * FROM (SELECT PHONE_NUMBER FROM PERSONAL_INFO ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.VOLUNTEERS (VOLUNTEER_ID, JOIN_DATE, NAME, ROLE_ID, GEAR_ID, PHONE_NUMBER)
values (269124115, to_date('30-01-2023', 'dd-mm-yyyy'), 'LukeAddy', (SELECT * FROM (SELECT Role_id FROM Position ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT GEAR_ID FROM GEAR ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1)), (SELECT * FROM (SELECT PHONE_NUMBER FROM PERSONAL_INFO ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (232114619, 'praseodymium', 'SVA-USA VR-15B 15" TFT LCD Display.');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (493598781, 'aluminum', 'Epson Stylus C42UX - C11C482001.');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (396191534, 'tin', 'C Rimm');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (729727741, 'berkelium', 'Intel P4 2.4ghz');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (247776350, 'argon', '512Mb DDR PC2100 Kingston');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (703753425, 'tellurium', 'Maxtor 30GB 7200RPM ATA133');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (494230268, 'sodium', 'Combo AMD XP 2600+ CPU; Gigabyte GA-7N400Pro M/B(W/DDR400 up to 3GB/ATA133 Raid/USB2.0) +Fan.');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (213813561, 'protactinium', 'Logitech Quick Cam W/Free Headset');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (804353072, 'silver', 'AMD Server Solution YS XP2000+ 266 FSB Raid Server');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (798489035, 'aluminum', '313G-B ATX case 400W P4/AMD Free Fan and 2 Front USB.');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (204853963, 'silicon', 'AMD 1.3Ghz BareBone System Free Mouse');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (274368930, 'tellurium', '256Mb DDR PC2100 (Micron)');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (214848823, 'bromine', 'Biostar M6VLB Intel PPGA (w/30day limit warranty)');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (506606598, 'lutetium', 'AMD Duron 1.3 Ghz (Oem)');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (465173450, 'beryllium', 'Case Fan 3 1/2"(80mm) 12V');

insert into SYSTEM.POSITION (ROLE_ID, ROLE_NAME, DESCRIPTION)
values (798660602, 'hafnium', 'Intel P4 1;6Ghz Bare Bone');





insert into SYSTEM.BASE (BASE_ID, LOCATION, DESCRIPTION)
values (507000726, 'Johor Bahru', 'Gigabyte GA-7NNXP MotherBoard w/ Nforce2 400 chipset.');

insert into SYSTEM.BASE (BASE_ID, LOCATION, DESCRIPTION)
values (572359502, 'San Jose', 'Seagate 40GB 5400RPM ATA100');

insert into SYSTEM.BASE (BASE_ID, LOCATION, DESCRIPTION)
values (590828483, 'Salem', 'AMD XP 1800+ & Biostar M7VIG-Pro MB w/ 313M case. Free PS2 Mouse.');

insert into SYSTEM.BASE (BASE_ID, LOCATION, DESCRIPTION)
values (776165925, 'Koblenz', 'MITSUMI 54X CD-Rom Black.');

insert into SYSTEM.BASE (BASE_ID, LOCATION, DESCRIPTION)
values (319502734, 'Reno', 'AMD Duron 1.3Ghz & Gigabyte GA-7VKMLE MB w/ 312D Color Case. W/ Free PS2 Mouse.');

insert into SYSTEM.BASE (BASE_ID, LOCATION, DESCRIPTION)
values (910326523, 'Trumbull', 'White RF Wireless Keyboard Track Ball .(PS/2 Connector)');

insert into SYSTEM.BASE (BASE_ID, LOCATION, DESCRIPTION)
values (297966294, 'Gattico', 'AMD Duron 1.3MHz & Biostar M7VIG-Pro MB w/ 312D case. Free PS2 Mouse.');

insert into SYSTEM.BASE (BASE_ID, LOCATION, DESCRIPTION)
values (178020654, 'Kejae City', 'Cyber Power 725VA Battery Back Up');

insert into SYSTEM.BASE (BASE_ID, LOCATION, DESCRIPTION)
values (965163105, 'Newbury', '5ft Cat5 network cable w/RJ45 connectors');

insert into SYSTEM.BASE (BASE_ID, LOCATION, DESCRIPTION)
values (902950807, 'Bartlesville', 'Combo AMD XP 2600+ CPU; Gigabyte GA-7VR M/B(W/DDR333 up to 3GB/ATA133) .');

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (RD-024, RD-024, 962755274);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (ML-023, ML-023, 562873311);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (MB-002, MB-002, 663621923);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (CMA-142, CMA-142, 419271397);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (CMA-161, CMA-161, 733667566);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (FD-003, FD-003, 167671799);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (ABB-096, ABB-096, 748207750);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (CMA-100, CMA-100, 570601863);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (CMA-110, CMA-110, 961392937);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (CS-078, CS-078, 355993065);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (NC-001, NC-001, 325758064);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (CMA-141, CMA-141, 593420023);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (CMI-120, CMI-120, 485697889);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (CP-028, CP-028, 918484044);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (ABB-098, ABB-098, 374555605);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (YS-029, YS-029, 247528697);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (MS-002, MS-002, 470012255);

insert into SYSTEM.GEAR (ARMOR_TYPE, GUN_TYPE, GEAR_ID)
values (IBB-022, IBB-022, 449874923);

insert into SYSTEM.PERSONAL_INFO (ADDRESS, PHONE_NUMBER, EMAIL)
values ('26957', 538998287, 'harold.rollins@streetglow.com');

insert into SYSTEM.PERSONAL_INFO (ADDRESS, PHONE_NUMBER, EMAIL)
values ('3514DK', 531417523, 'taye.crimson@elitemedical.nl');

insert into SYSTEM.PERSONAL_INFO (ADDRESS, PHONE_NUMBER, EMAIL)
values ('32716', 535023939, 'jake.shand@nhhc.dk');

insert into SYSTEM.PERSONAL_INFO (ADDRESS, PHONE_NUMBER, EMAIL)
values ('11798', 535201112, 'carlene.sanchez@slt.com');

insert into SYSTEM.PERSONAL_INFO (ADDRESS, PHONE_NUMBER, EMAIL)
values ('32960', 534120321, 'mrain@deutschetelekom.it');

insert into SYSTEM.PERSONAL_INFO (ADDRESS, PHONE_NUMBER, EMAIL)
values ('5137OK', 539079247, 'tal.postlethwaite@telepoint.nl');

insert into SYSTEM.PERSONAL_INFO (ADDRESS, PHONE_NUMBER, EMAIL)
values ('26001', 530432689, 'winona.r@enterprise.com');

insert into SYSTEM.PERSONAL_INFO (ADDRESS, PHONE_NUMBER, EMAIL)
values ('14733', 534400472, 'nelly.w@bioreference.in');

insert into SYSTEM.PERSONAL_INFO (ADDRESS, PHONE_NUMBER, EMAIL)
values ('9556', 531463711, 'pat.boothe@bis.be');

insert into SYSTEM.PERSONAL_INFO (ADDRESS, PHONE_NUMBER, EMAIL)
values ('8146', 537215909, 'sal.pfeiffer@unilever.com');

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (987503490, to_date('11-05-2023', 'dd-mm-yyyy'), to_date('01-03-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (284587135, to_date('20-04-2023', 'dd-mm-yyyy'), to_date('09-06-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (774408669, to_date('05-07-2023', 'dd-mm-yyyy'), to_date('21-08-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (169291581, to_date('25-12-2023', 'dd-mm-yyyy'), to_date('16-10-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (586044195, to_date('22-04-2023', 'dd-mm-yyyy'), to_date('11-02-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (740584609, to_date('05-12-2023', 'dd-mm-yyyy'), to_date('25-08-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (427309738, to_date('05-01-2023', 'dd-mm-yyyy'), to_date('02-08-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (240377692, to_date('18-03-2023', 'dd-mm-yyyy'), to_date('21-12-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (171828864, to_date('22-04-2023', 'dd-mm-yyyy'), to_date('01-02-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (848407816, to_date('16-08-2023', 'dd-mm-yyyy'), to_date('29-10-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (763772646, to_date('02-06-2023', 'dd-mm-yyyy'), to_date('20-10-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (782650423, to_date('23-08-2023', 'dd-mm-yyyy'), to_date('30-04-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (327094478, to_date('11-04-2023', 'dd-mm-yyyy'), to_date('03-05-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (455819080, to_date('27-08-2023', 'dd-mm-yyyy'), to_date('25-01-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (596543751, to_date('02-05-2023', 'dd-mm-yyyy'), to_date('21-08-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (421411352, to_date('05-06-2023', 'dd-mm-yyyy'), to_date('28-09-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (540392487, to_date('23-10-2023', 'dd-mm-yyyy'), to_date('09-04-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (888561144, to_date('23-09-2023', 'dd-mm-yyyy'), to_date('28-11-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (669906658, to_date('21-11-2023', 'dd-mm-yyyy'), to_date('14-12-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SHIFTS (SHIFT_ID, START_DATE_TIME, END_DATE_TIME, BASE_ID)
values (622164767, to_date('18-08-2023', 'dd-mm-yyyy'), to_date('06-06-2023', 'dd-mm-yyyy'), (SELECT * FROM (SELECT BASE_ID FROM BASE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

insert into SYSTEM.SIGNED_UP (VOLUNTEER_ID, SHIFT_ID)
values ((SELECT * FROM (SELECT VOLUNTEER_ID FROM VOLUNTEERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1), (SELECT * FROM (SELECT SHIFT_ID FROM SHIFTS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));

commit;
